// R23.7C-C — Canonical Image Serving Contract.
//
// Certifies the fix for the BROKEN_SUCCESS_CONTRACT root-cause audit: an
// ImageExecutor-completed image's returned openTarget
// (/api/v1/creations/images/:imageId) must actually be servable through
// the real HTTP dispatch path (handleCreationRoutes), not just present as
// a string in the response body. Uses a deterministic fake provider with
// known bytes — no real OpenAI call.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { ImageExecutor } from '../src/creation/executors/image-executor.js';
import { ImageStore } from '../src/creation/image.store.js';
import { ArtifactStore } from '../src/artifacts/artifact.store.js';
import { CreationProviderRouter } from '../src/creation/providers/creation-provider-router.js';
import type { ImageProviderPort, ImageProviderCapabilities } from '../src/creation/providers/creation-provider.types.js';
import { AuditLogger } from '../src/governance/audit.logger.js';
import { CreationStore } from '../src/creation/creation.store.js';
import { CreationService } from '../src/creation/creation.service.js';
import { handleCreationRoutes } from '../src/http/routes/creation.routes.js';
import { authAs } from './_s1_session_auth.js';

const KNOWN_IMAGE_BYTES = Buffer.from('deterministic-known-png-bytes-for-r23-7c-c');

function createFakeProvider(providerId = 'fake-openai'): ImageProviderPort {
  const caps: ImageProviderCapabilities = {
    textToImage: true,
    imageToImage: true,
    editingInpainting: true,
    referenceImageConditioning: true,
    transparentBackground: true,
    textRendering: true,
    supportedAspectRatios: ['1:1', '16:9'],
    maxReferenceImages: 3,
  };
  return {
    providerId,
    getStatus: () => 'AVAILABLE',
    getCapabilities: () => caps,
    generateImage: async () => ({
      status: 'COMPLETED',
      output: { imageBuffer: KNOWN_IMAGE_BYTES, mimeType: 'image/png', temporaryUrl: 'https://fake-provider.com/temp/image.png' },
      metadata: { providerId, createdAt: new Date().toISOString() },
    }),
  };
}

function setup() {
  const imageStore = new ImageStore();
  const artifactStore = new ArtifactStore();
  const providerRouter = new CreationProviderRouter();
  const auditLogger = new AuditLogger();
  providerRouter.registerImageProvider(createFakeProvider());
  const imageExecutor = new ImageExecutor({ imageStore, artifactStore, providerRouter, auditLogger });
  const creationStore = new CreationStore();
  const creationService = new CreationService(creationStore, auditLogger);
  return { imageStore, artifactStore, imageExecutor, creationService };
}

async function createImage(deps: ReturnType<typeof setup>, tenantId: string, ownerId: string) {
  return handleCreationRoutes(
    'POST',
    '/api/v1/creations/generate',
    { prompt: 'Canonical serving test', type: 'IMAGE' },
    authAs(tenantId, ownerId),
    {},
    { creationService: deps.creationService, imageExecutor: deps.imageExecutor, imageStore: deps.imageStore },
  );
}

function getImage(deps: ReturnType<typeof setup>, imageUrl: string, tenantId: string, ownerId: string) {
  return handleCreationRoutes(
    'GET',
    imageUrl,
    null,
    authAs(tenantId, ownerId),
    {},
    { creationService: deps.creationService, imageExecutor: deps.imageExecutor, imageStore: deps.imageStore },
  );
}

test('1. POST /creations/generate (IMAGE) returns 201/COMPLETED with a real imageUrl', async () => {
  const deps = setup();
  const res = await createImage(deps, 'ten_a', 'usr_a');
  assert.ok(res);
  assert.equal(res!.status, 201);
  const data = res!.data as any;
  assert.equal(data.status, 'COMPLETED');
  assert.ok(data.creationId);
  assert.ok(data.artifactId);
  assert.ok(data.imageUrl.startsWith('/api/v1/creations/images/'));
});

test('2. GET the returned imageUrl with the same tenant/principal returns 200, correct Content-Type, byte-identical content', async () => {
  const deps = setup();
  const created = await createImage(deps, 'ten_a', 'usr_a');
  const imageUrl = (created!.data as any).imageUrl as string;

  const res = await getImage(deps, imageUrl, 'ten_a', 'usr_a');
  assert.ok(res);
  assert.equal(res!.status, 200);
  assert.equal((res as any).isBinary, true);
  assert.equal((res as any).contentType, 'image/png');
  assert.ok(Buffer.isBuffer(res!.data));
  assert.ok((res!.data as Buffer).equals(KNOWN_IMAGE_BYTES), 'served bytes must be byte-identical to the provider-generated bytes');
});

test('3. GET with the wrong tenant is denied (404), never discloses the image exists', async () => {
  const deps = setup();
  const created = await createImage(deps, 'ten_a', 'usr_a');
  const imageUrl = (created!.data as any).imageUrl as string;

  const res = await getImage(deps, imageUrl, 'ten_victim', 'usr_a');
  assert.ok(res);
  assert.equal(res!.status, 404);
  assert.equal((res as any).isBinary, undefined);
});

test('4. GET with the wrong owner (same tenant) is denied (404), never discloses the image exists', async () => {
  const deps = setup();
  const created = await createImage(deps, 'ten_a', 'usr_a');
  const imageUrl = (created!.data as any).imageUrl as string;

  const res = await getImage(deps, imageUrl, 'ten_a', 'usr_victim');
  assert.ok(res);
  assert.equal(res!.status, 404);
});

test('5. GET an unknown imageId returns 404', async () => {
  const deps = setup();
  const res = await getImage(deps, '/api/v1/creations/images/img_does_not_exist', 'ten_a', 'usr_a');
  assert.ok(res);
  assert.equal(res!.status, 404);
});

test('6. the generic GET /api/v1/creations/:id route remains unaffected for a non-image creationId', async () => {
  const deps = setup();
  const res = await handleCreationRoutes(
    'GET',
    '/api/v1/creations/some_other_creation_id',
    null,
    authAs('ten_a', 'usr_a'),
    {},
    { creationService: deps.creationService, imageExecutor: deps.imageExecutor, imageStore: deps.imageStore },
  );
  assert.ok(res);
  assert.equal(res!.status, 404);
  assert.equal((res!.data as any).error, 'CREATION_NOT_FOUND');
});

test('7. the generic GET /api/v1/creations/:id route never matches an /images/ path (route precedence)', async () => {
  const deps = setup();
  const created = await createImage(deps, 'ten_a', 'usr_a');
  const imageUrl = (created!.data as any).imageUrl as string;

  // If route precedence were wrong, this would 404 with CREATION_NOT_FOUND
  // (the exact original bug) instead of serving the real binary.
  const res = await getImage(deps, imageUrl, 'ten_a', 'usr_a');
  assert.equal(res!.status, 200);
  assert.notEqual((res!.data as any)?.error, 'CREATION_NOT_FOUND');
});
