// Phase 01 — Composition Root Refactoring.
//
// NagexApplication is a plain, explicit-typed application object graph — not
// a framework, not a service locator, not a generic container. Every field
// here is a production singleton `server_web.ts` already constructed inline
// before this refactor; this type only names the shape once so
// createNagexApplication() has something concrete to return and
// server_web.ts has something concrete to destructure from.
import type { PolicyDecisionPoint } from '../identity/pdp.js';
import type { DurableRuntimeEngine } from '../runtime/runtime.engine.js';
import type { AuditLogger } from '../governance/audit.logger.js';
import type { BillingLedgerEngine } from '../billing/billing.ledger.js';
import type { CreditEngine } from '../billing/credit.engine.js';
import type { MemoryEngine, MemoryRecord } from '../context/memory.engine.js';
import type { PersonalContextService } from '../context/personal-context.service.js';
import type { ConversationMemoryExtractor } from '../context/conversation-memory-extractor.js';
import type { AiService } from '../model-gateway/ai-service.js';
import type { PlanResolver } from '../planning/plan-resolver.js';
import type { PersistentActionApprovalStore } from '../governance/action-approval.store.js';
import type { ExecutionStore } from '../governance/execution.store.js';
import type { GoogleCalendarService } from '../modules/calendar/index.js';
import type { GmailService } from '../modules/gmail/index.js';
import type { BrowserToolService } from '../modules/browser/index.js';
import type { CapabilityBroker } from '../capabilities/index.js';
import type { SessionStore } from '../sessions/session.store.js';
import type { ConversationStore } from '../conversations/conversation.store.js';
import type { ConversationContextService } from '../conversations/conversation-context.service.js';
import type { TaskStore } from '../tasks/task.store.js';
import type { TaskRunStore } from '../tasks/task-run.store.js';
import type { TaskScheduler } from '../tasks/task.scheduler.js';
import type { CompositeTaskRunner } from '../tasks/task.runner.js';
import type { TaskContinuationStore } from '../tasks/task-continuation.store.js';
import type { TaskContinuationCoordinator } from '../tasks/task-continuation.coordinator.js';
import type { DurableTaskRunStateStore } from '../tasks/durable-task-run-state.store.js';
import type { DurableTaskRuntime } from '../tasks/durable-task-runtime.js';
import type { TelegramIdentityStore } from '../integrations/telegram/telegram-identity.store.js';
import type { TelegramBotClient } from '../integrations/telegram/telegram.client.js';
import type { TelegramService } from '../integrations/telegram/telegram.service.js';
import type { SlackIdentityStore } from '../integrations/slack/slack-identity.store.js';
import type { SlackClient } from '../integrations/slack/slack.client.js';
import type { SlackService } from '../integrations/slack/slack.service.js';
import type { DesktopRuntimeEngine } from '../desktop/desktop-runtime.engine.js';
import type { NotificationStore } from '../notifications/notification.store.js';
import type { NotificationEngine } from '../notifications/notification.engine.js';
import type { KnowledgeEngine } from '../context/knowledge.engine.js';
import type { StorageProvider } from '../storage/storage-provider.js';
import type { CandidateStore } from '../workspace/candidate.store.js';
import type { ActivityStore } from '../governance/activity.store.js';
import type { DailyBriefStore } from '../governance/daily-brief.store.js';
import type { ActionProposalStore } from '../assistant/action-proposal.store.js';
import type { CandidateActionResolver } from '../workspace/action-resolver.js';
import type { QuickCaptureService } from '../workspace/quick-capture.service.js';
import type { InputRouter } from '../workspace/input-router.js';
import type { LifecycleManager } from './lifecycle-manager.js';
import type { ModuleRegistry, ModuleStateStore, ModuleService } from '../modules/index.js';
import type { WorkflowDefinitionStore } from '../workflows/workflow-definition.store.js';
import type { WorkflowDefinitionService } from '../workflows/workflow-definition.service.js';
import type { CreationStore } from '../creation/creation.store.js';
import type { CreationService } from '../creation/creation.service.js';
import type { LinkCaptureService } from '../capture/link-capture.service.js';
import type { InboxStore } from '../workspace/inbox.store.js';
import type { VaultStore } from '../workspace/vault.store.js';
import type { ConnectionStore } from '../workspace/connections.store.js';
import type { ActionStore } from '../workspace/action.store.js';
import type { ActionExecutionEngine } from '../actions/action-execution.engine.js';
import type { DeviceExecutionSessionStore } from '../device-control/device-execution-session.store.js';
import type { DeviceControlService } from '../device-control/device-control.service.js';
import type { DeviceIdentityStore } from '../device-agent/device-identity.store.js';
import type { DesktopExecutionSessionStore } from '../device-agent/desktop-execution-session.store.js';
import type { DeviceTransportSecurity } from '../device-agent/device-transport-security.js';
import type { DeviceConnectionStatusStore } from '../device-agent/device-connection-status.store.js';
import type { DevicePendingCommandStore } from '../device-agent/device-pending-command.store.js';
import type { DeviceAgentTransportEndpoint } from '../device-agent/device-agent-transport-endpoint.service.js';

import type { IdentityStore } from '../identity/identity.store.js';
import type { IdentityTokenStore } from '../identity/identity.tokens.js';
import type { IdentityAuditStore } from '../identity/identity.audit.js';
import type { OrganizationStore } from '../organizations/organization.store.js';
import type { RbacStore } from '../rbac/rbac.store.js';
import type { RbacService } from '../rbac/rbac.service.js';
import type { EnterpriseIdentityStore } from '../enterprise-identity/enterprise-identity.store.js';
import type { SsoFlowStore } from '../enterprise-identity/sso-flow.store.js';
import type { SocialIdentityStore } from '../identity/social-identity.store.js';

import type { PersonalReminderStore } from '../personal/personal-reminder.store.js';
import type { PersonalAssistantEngine } from '../personal/personal-assistant.engine.js';
import type { DemoScenarioService } from '../demo/demo-scenario.service.js';
import type { QuestionClassificationService } from '../research/question-classification.service.js';
import type { WebSearchService } from '../research/web-search.service.js';
import type { EvidencePackService } from '../research/evidence-pack.service.js';

export interface NagexApplication {
  questionClassificationService: QuestionClassificationService;
  webSearchService: WebSearchService;
  evidencePackService: EvidencePackService;
  demoScenarioService: DemoScenarioService;
  personalReminderStore: PersonalReminderStore;
  personalAssistantEngine: PersonalAssistantEngine;
  identityStore: IdentityStore;
  identityTokenStore: IdentityTokenStore;
  identityAuditStore: IdentityAuditStore;
  organizationStore: OrganizationStore;
  rbacStore: RbacStore;
  rbacService: RbacService;
  enterpriseIdentityStore: EnterpriseIdentityStore;
  ssoFlowStore: SsoFlowStore;
  socialIdentityStore: SocialIdentityStore;
  pdp: PolicyDecisionPoint;
  runtime: DurableRuntimeEngine;
  auditLogger: AuditLogger;
  billing: BillingLedgerEngine;
  creditEngine: CreditEngine;
  memoryEngine: MemoryEngine;
  personalContextService: PersonalContextService;
  conversationMemoryExtractor: ConversationMemoryExtractor;
  aiService: AiService;
  planResolver: PlanResolver;
  actionApprovals: PersistentActionApprovalStore;
  executionStore: ExecutionStore;
  googleCalendarService: GoogleCalendarService;
  gmailService: GmailService;
  browserService: BrowserToolService;
  moduleRegistry: ModuleRegistry;
  moduleStateStore: ModuleStateStore;
  moduleService: ModuleService;
  capabilityBroker: CapabilityBroker;
  sessionStore: SessionStore;
  conversationStore: ConversationStore;
  conversationContextService: ConversationContextService;
  taskStore: TaskStore;
  taskRunStore: TaskRunStore;
  taskRunner: CompositeTaskRunner;
  taskScheduler: TaskScheduler;
  taskContinuations: TaskContinuationStore;
  taskContinuationCoordinator: TaskContinuationCoordinator;
  durableTaskRunState: DurableTaskRunStateStore;
  durableTaskRuntime: DurableTaskRuntime;
  telegramIdentityStore: TelegramIdentityStore;
  telegramBotClient: TelegramBotClient;
  telegramService: TelegramService;
  slackIdentityStore: SlackIdentityStore;
  slackClient: SlackClient;
  slackService: SlackService;
  desktopRuntimeEngine: DesktopRuntimeEngine;
  notificationStore: NotificationStore;
  notificationEngine: NotificationEngine;
  knowledgeEngine: KnowledgeEngine;
  storageProvider: StorageProvider;
  candidateStore: CandidateStore;
  activityStore: ActivityStore;
  dailyBriefStore: DailyBriefStore;
  actionProposalStore: ActionProposalStore;
  candidateActionResolver: CandidateActionResolver;
  quickCaptureService: QuickCaptureService;
  inputRouter: InputRouter;
  workflowDefinitionStore: WorkflowDefinitionStore;
  workflowDefinitionService: WorkflowDefinitionService;
  creationStore: CreationStore;
  creationService: CreationService;
  linkCaptureService: LinkCaptureService;
  inboxStore: InboxStore;
  vaultStore: VaultStore;
  connectionStore: ConnectionStore;
  actionStore: ActionStore;
  actionEngine: ActionExecutionEngine;
  deviceExecutionSessionStore: DeviceExecutionSessionStore;
  deviceControlService: DeviceControlService | undefined;
  deviceIdentityStore: DeviceIdentityStore;
  desktopExecutionSessionStore: DesktopExecutionSessionStore;
  deviceTransportSecurity: DeviceTransportSecurity;
  deviceConnectionStatusStore: DeviceConnectionStatusStore;
  devicePendingCommandStore: DevicePendingCommandStore;
  deviceAgentTransportEndpoint: DeviceAgentTransportEndpoint;
  getRelevantMemories: (tenantId: string, principalId: string, prompt: string) => MemoryRecord[];
  pinnedMemories: Set<string>;
  lifecycle: LifecycleManager;
  modelRouter: import('../model-gateway/unified-model-router.js').UnifiedModelRouter;
  perspectiveCompareService: import('../model-gateway/perspective-compare.service.js').PerspectiveCompareService;
  forecastCompareService: import('../model-gateway/forecast-compare.service.js').ForecastCompareService;
  personalHomeService: import('../home/personal-home.service.js').PersonalHomeService;
  currentPersonalContextService: import('../personal/current-personal-context.service.js').CurrentPersonalContextService;
  /** Re-seeds the canonical demo persona memory into the real MemoryEngine. Call after demo reset. */
  seedDemoMemory(): void;
}
