// R10.2-D Increment 4 — Governance/billing routes (executions, billing,
// audit logs), extracted verbatim from server_web.ts. executions POST is
// the one real ADMIN/SYSTEM mutation here (PDP-authorized agent execution
// + credit charge); everything else is READ_ONLY. ensureTenantSeeded/
// INITIAL_CREDIT_GRANT/MANAGED_AI_COST_BREAKDOWN/SUBSCRIPTION_INFO/
// executionHistory moved here with their only remaining consumers — grep
// confirmed no other route touches them (executionHistory's read-only
// length is still exposed to health.routes.ts via a getter passed in from
// server_web.ts, since that domain legitimately needs it too).
import type { PolicyDecisionPoint } from '../../identity/pdp.js';
import { describeDeniedDecision } from '../../identity/pdp.js';
import type { DurableRuntimeEngine } from '../../runtime/runtime.engine.js';
import type { AuditLogger } from '../../governance/audit.logger.js';
import type { CreditEngine, CreditCostBreakdown } from '../../billing/credit.engine.js';
import { computeCreditCost, sumBreakdownUsd } from '../../billing/credit.engine.js';
import { NagexError } from '../../common/errors.js';
import type { TenantContext, PrincipalReference } from '../../common/types.js';
import type { ApiResult, SyncRouteRegistrar } from '../http-types.js';

export const INITIAL_CREDIT_GRANT = 10000;
const seededTenants = new Set<string>();

export const MANAGED_AI_COST_BREAKDOWN: CreditCostBreakdown = {
  llm_cost_unit: 0.04,
  rag_unit: 0.004,
  tool_unit: 0.005,
  runtime_unit: 0.011,
};

const SUBSCRIPTION_INFO = {
  plan: 'Business Pro',
  monthly_price: 120.0,
  next_renewal: '2026-09-01',
};

// In-memory Execution History (legacy demo seed + real /executions writes)
export const executionHistory: Array<Record<string, unknown>> = [
  {
    execution_id: 'exec_meeting_prep_001',
    agent_id: 'agt_personal_ai',
    agent_name: 'NAgex Personal AI',
    objective: 'Prepare my next client meeting and schedule it.',
    status: 'COMPLETED',
    tenant_id: 'ten_production_01',
    created_at: new Date(Date.now() - 600000).toISOString(),
    checkpoint: 'COMPLETED',
    steps_log: [
      'Goal received: Prepare client meeting and schedule it',
      'Memory loaded: Relevant context retrieved (12 memories)',
      'Plan created: 8 steps generated by NAgex',
      'Skill selected: Meeting Preparation',
      'Tool selected: Google Calendar & Gmail',
      'Approval requested: Step 5 - Get stakeholder review',
      'Approval granted by user',
      'Tool executed: Research completed with Perplexity',
      'Result verified: Calendar event registered',
      'Memory updated: Saved meeting briefing preference',
    ],
  },
];

function ensureTenantSeeded(tenantId: string, creditEngine: CreditEngine): void {
  if (!seededTenants.has(tenantId)) {
    creditEngine.grantCredits(tenantId, INITIAL_CREDIT_GRANT, 'Initial account seed');
    seededTenants.add(tenantId);
  }
}

export interface GovernanceRouteDeps {
  pdp: PolicyDecisionPoint;
  runtime: DurableRuntimeEngine;
  auditLogger: AuditLogger;
  creditEngine: CreditEngine;
  tenantId: string;
  tenantContext: TenantContext;
  principal: PrincipalReference;
}

export const handleGovernanceRoutes: SyncRouteRegistrar<GovernanceRouteDeps> = (method, pathname, body, headers, _query, deps): ApiResult | undefined => {
  const { pdp, runtime, auditLogger, creditEngine, tenantId, tenantContext, principal } = deps;

  if (pathname === '/api/v1/executions' && method === 'POST') {
    const taskObjective = (body?.objective as string) || 'Unnamed task';
    const agentId = (body?.agent_id as string) || 'agt_personal_ai';
    const headerRequestId = headers['x-request-id'] || headers['X-Request-Id'];
    const requestId = (Array.isArray(headerRequestId) ? headerRequestId[0] : headerRequestId) || `req_${Date.now()}`;

    const decision = pdp.evaluate({ principal, tenant_context: tenantContext, action: 'agent:execute', resource_type: 'Agent', resource_id: agentId, principal_permissions: ['agent:execute'] });
    if (decision.decision !== 'ALLOW') {
      const outcome = describeDeniedDecision(decision);
      auditLogger.logEvent({ actor: principal, tenant_id: tenantId, action: 'agent:execute', resource: { type: 'Agent', id: agentId }, result: outcome.auditResult, reason_code: decision.reason_code, request_id: requestId });
      return { status: outcome.httpStatus, data: { error: outcome.errorCode, reason: decision.reason_code, request_id: requestId } };
    }

    ensureTenantSeeded(tenantId, creditEngine);
    try {
      creditEngine.chargeCredits(tenantId, MANAGED_AI_COST_BREAKDOWN, `pending_${requestId}`);
    } catch (err) {
      if (err instanceof NagexError && err.code === 'BILLING_INSUFFICIENT_CREDIT') {
        return { status: 402, data: { error: err.code, message: err.message, request_id: requestId } };
      }
      throw err;
    }

    const execution = runtime.createExecution(tenantContext, agentId);
    auditLogger.logEvent({ actor: principal, tenant_id: tenantId, action: 'agent:execute', resource: { type: 'Execution', id: execution.id }, result: 'SUCCESS', request_id: requestId });

    const record = { execution_id: execution.id, agent_id: agentId, agent_name: 'NAgex Personal AI', objective: taskObjective, status: execution.state, tenant_id: tenantId, created_at: new Date().toISOString(), checkpoint: 'INITIAL', request_id: requestId };
    executionHistory.unshift(record);
    return { status: 201, data: record };
  }

  if (pathname === '/api/v1/billing/usage' && method === 'GET') {
    ensureTenantSeeded(tenantId, creditEngine);
    const account = creditEngine.getOrCreateAccount(tenantId);
    return { status: 200, data: { ...SUBSCRIPTION_INFO, total_credits: INITIAL_CREDIT_GRANT, used_credits: INITIAL_CREDIT_GRANT - account.credit_balance, remaining_credits: account.credit_balance } };
  }
  if (pathname === '/api/v1/billing/estimate' && method === 'POST') return { status: 200, data: { providerMode: 'NAGEX_MANAGED', estimatedCredits: computeCreditCost(MANAGED_AI_COST_BREAKDOWN), estimatedProviderCost: sumBreakdownUsd(MANAGED_AI_COST_BREAKDOWN), currency: 'USD' } };
  if (pathname === '/api/v1/audit/logs' && method === 'GET') {
    const logs = auditLogger.getAuditLogs(tenantId, 20);
    return { status: 200, data: { logs, total: logs.length } };
  }
  if (pathname === '/api/v1/executions' && method === 'GET') return { status: 200, data: { executions: executionHistory, total: executionHistory.length } };

  return undefined;
};
