// R16 §11-14 — SAML 2.0 SP-initiated SSO: AuthnRequest generation and
// real, from-scratch SAML Response verification (no XML/SAML library
// exists anywhere in this codebase or its dependencies — see the R16
// investigation report; this follows the same "hand-roll with
// node:crypto" convention the OIDC module and device-transport-security.ts
// already use, rather than introducing this project's first XML
// dependency).
//
// SCOPE / HONEST LIMITATION (documented here and in the R16 completion
// report, not hidden): this parser is intentionally a strict, narrow
// ALLOWLIST extractor, not a general XML/XPath engine. It requires
// EXACTLY one <Assertion> and EXACTLY one <Signature> block anywhere in
// the response and rejects the response outright if either count is not
// exactly 1 — this is itself the primary defense against XML Signature
// Wrapping attacks (a wrapping attack fundamentally relies on smuggling a
// second, attacker-controlled assertion alongside or nested around the
// legitimately-signed one; an extractor that refuses to process a
// response containing more than one Assertion or Signature cannot be
// tricked into reading the wrong one). Digest and signature verification
// is real (SHA-256 digest of the canonicalized assertion body, RSA-SHA256
// signature over the SignedInfo block, verified against the ADMINISTRATOR-
// CONFIGURED certificate — an embedded KeyInfo certificate, if present in
// the response, is never trusted for verification, only optionally used
// for a stored fingerprint sanity check). It has NOT been validated
// against the full SAML conformance/interop test suite and does not
// implement arbitrary XML Canonicalization (only the single enveloped-
// signature transform pattern real IdPs commonly produce for a
// single-level Assertion). Interop with an IdP whose XML serialization
// disagrees at the byte level (attribute reordering, extra namespace
// declarations inside the signed region) will fail digest verification
// and DENY the login (fail closed) rather than silently accepting an
// unverified assertion — that fail-closed behavior is the load-bearing
// security property; broader canonicalization support is the honestly-
// registered gap (see docs/TECHNICAL_DEBT_REGISTRY.md DEBT-0007).
import crypto from 'node:crypto';
import zlib from 'node:zlib';
import { NagexError } from '../common/errors.js';
import type { SamlProviderConfig } from './enterprise-identity.types.js';

export interface SamlAuthnRequestResult {
  requestId: string;
  redirectUrl: string;
}

export function generateSamlRequestId(): string {
  return `_${crypto.randomBytes(16).toString('hex')}`;
}

// requestId is generated by the CALLER (not internally) so it can be
// persisted alongside the flow/RelayState record before the redirect is
// issued — the ACS callback needs that same id to validate InResponseTo.
export function buildAuthnRequest(config: SamlProviderConfig, spEntityId: string, acsUrl: string, relayState: string, requestId: string): SamlAuthnRequestResult {
  const issueInstant = new Date().toISOString();
  const xml = `<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="${requestId}" Version="2.0" IssueInstant="${issueInstant}" Destination="${escapeXmlAttr(config.ssoUrl)}" AssertionConsumerServiceURL="${escapeXmlAttr(acsUrl)}" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"><saml:Issuer>${escapeXmlText(spEntityId)}</saml:Issuer></samlp:AuthnRequest>`;
  const deflated = zlib.deflateRawSync(Buffer.from(xml, 'utf8'));
  const encoded = deflated.toString('base64');
  const url = new URL(config.ssoUrl);
  url.searchParams.set('SAMLRequest', encoded);
  url.searchParams.set('RelayState', relayState);
  return { requestId, redirectUrl: url.toString() };
}

function escapeXmlAttr(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}
function escapeXmlText(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function countOccurrences(haystack: string, tagLocalName: string): number {
  const re = new RegExp(`<(?:[A-Za-z0-9]+:)?${tagLocalName}(?:\\s[^>]*)?>`, 'g');
  return (haystack.match(re) || []).length;
}

function extractBlock(xml: string, tagLocalName: string): { full: string; inner: string; attrs: string } | null {
  // Matches either a self-closing element (<Tag attrs/>) or an opening
  // tag (<Tag attrs>) — real SAML responses commonly use self-closing
  // tags for attribute-only, no-children elements like
  // SubjectConfirmationData, so both forms must be handled.
  const openRe = new RegExp(`<((?:[A-Za-z0-9]+:)?${tagLocalName})((?:\\s[^>]*?)?)(/?)>`, '');
  const openMatch = openRe.exec(xml);
  if (!openMatch) return null;
  const fullTagName = openMatch[1];
  const attrs = openMatch[2];
  const isSelfClosing = openMatch[3] === '/';
  if (isSelfClosing) {
    const full = openMatch[0];
    return { full, inner: '', attrs };
  }
  const closeTag = `</${fullTagName}>`;
  const closeIdx = xml.indexOf(closeTag, openMatch.index);
  if (closeIdx === -1) return null;
  const full = xml.slice(openMatch.index, closeIdx + closeTag.length);
  const innerStart = openMatch.index + openMatch[0].length;
  const inner = xml.slice(innerStart, closeIdx);
  return { full, inner, attrs };
}

function extractAttr(attrString: string, name: string): string | null {
  const re = new RegExp(`${name}="([^"]*)"`);
  const m = re.exec(attrString);
  return m ? m[1] : null;
}

function extractText(xml: string, tagLocalName: string): string | null {
  const block = extractBlock(xml, tagLocalName);
  return block ? block.inner.trim() : null;
}

export interface VerifiedSamlAssertion {
  nameId: string;
  issuer: string;
  attributes: Record<string, string>;
  sessionNotOnOrAfter: string | null;
}

export interface SamlVerifyOptions {
  organizationId: string;
  providerId: string;
  config: SamlProviderConfig;
  spEntityId: string;
  acsUrl: string;
  expectedInResponseTo: string;
  now?: number;
  isReplay: (responseId: string) => boolean; // true if this response/assertion id was already accepted before
}

// Decodes the base64 (HTTP-POST binding — no deflate, unlike the redirect-
// binding AuthnRequest) SAMLResponse form field into raw XML.
export function decodeSamlResponse(samlResponseBase64: string): string {
  return Buffer.from(samlResponseBase64, 'base64').toString('utf8');
}

export function verifySamlResponse(xml: string, options: SamlVerifyOptions): VerifiedSamlAssertion {
  const now = options.now ?? Date.now();
  const fail = (code: string, message: string): never => {
    throw new NagexError({ code, category: 'AUTHENTICATION', message });
  };

  // §13 — XML signature wrapping defense: reject outright if the response
  // does not contain EXACTLY one Assertion and EXACTLY one Signature.
  const assertionCount = countOccurrences(xml, 'Assertion');
  if (assertionCount !== 1) fail('SAML_MULTIPLE_ASSERTIONS', `Response must contain exactly one Assertion (found ${assertionCount}).`);
  const signatureCount = countOccurrences(xml, 'Signature');
  if (signatureCount !== 1) fail('SAML_MULTIPLE_SIGNATURES', `Response must contain exactly one Signature (found ${signatureCount}) — unsigned or multiply-signed responses are never accepted.`);

  const responseBlock = extractBlock(xml, 'Response');
  if (!responseBlock) fail('SAML_RESPONSE_MALFORMED', 'No <Response> element found.');
  const responseId = extractAttr(responseBlock!.attrs, 'ID');
  const inResponseTo = extractAttr(responseBlock!.attrs, 'InResponseTo');
  if (!responseId) fail('SAML_RESPONSE_MALFORMED', 'Response is missing an ID.');
  if (inResponseTo !== options.expectedInResponseTo) fail('SAML_IN_RESPONSE_TO_MISMATCH', 'InResponseTo does not match the AuthnRequest this SP issued — possible CSRF/replay.');

  const assertionBlock = extractBlock(responseBlock!.full, 'Assertion');
  if (!assertionBlock) fail('SAML_RESPONSE_MALFORMED', 'No <Assertion> element found.');
  const assertionId = extractAttr(assertionBlock!.attrs, 'ID');
  if (!assertionId) fail('SAML_RESPONSE_MALFORMED', 'Assertion is missing an ID.');

  // §54 — replay protection, checked against BOTH the outer Response id
  // and the inner Assertion id (either being reused is a replay).
  if (options.isReplay(responseId!) || options.isReplay(assertionId!)) {
    fail('SAML_REPLAY_DETECTED', 'This SAML Response/Assertion has already been accepted once.');
  }

  const issuer = extractText(responseBlock!.full, 'Issuer') ?? extractText(assertionBlock!.full, 'Issuer');
  if (!issuer || issuer !== options.config.entityId) fail('SAML_ISSUER_MISMATCH', 'Issuer does not match the configured provider entity_id.');

  const conditionsBlock = extractBlock(assertionBlock!.full, 'Conditions');
  if (!conditionsBlock) fail('SAML_ASSERTION_MALFORMED', 'Assertion is missing <Conditions>.');
  const notBefore = extractAttr(conditionsBlock!.attrs, 'NotBefore');
  const notOnOrAfter = extractAttr(conditionsBlock!.attrs, 'NotOnOrAfter');
  if (notBefore && new Date(notBefore).getTime() > now) fail('SAML_ASSERTION_NOT_YET_VALID', 'Assertion NotBefore is in the future.');
  if (notOnOrAfter && new Date(notOnOrAfter).getTime() <= now) fail('SAML_ASSERTION_EXPIRED', 'Assertion NotOnOrAfter has passed.');

  const audience = extractText(conditionsBlock!.full, 'Audience');
  if (!audience || audience !== options.spEntityId) fail('SAML_AUDIENCE_MISMATCH', 'Audience does not match this Service Provider\'s entity_id.');

  const subjectConfBlock = extractBlock(assertionBlock!.full, 'SubjectConfirmationData');
  if (!subjectConfBlock) fail('SAML_ASSERTION_MALFORMED', 'Assertion is missing <SubjectConfirmationData>.');
  const recipient = extractAttr(subjectConfBlock!.attrs, 'Recipient');
  const scdNotOnOrAfter = extractAttr(subjectConfBlock!.attrs, 'NotOnOrAfter');
  const scdInResponseTo = extractAttr(subjectConfBlock!.attrs, 'InResponseTo');
  if (recipient !== options.acsUrl) fail('SAML_RECIPIENT_MISMATCH', 'SubjectConfirmationData Recipient does not match this SP\'s Assertion Consumer Service URL.');
  if (scdInResponseTo !== options.expectedInResponseTo) fail('SAML_IN_RESPONSE_TO_MISMATCH', 'SubjectConfirmationData InResponseTo does not match the AuthnRequest this SP issued.');
  if (scdNotOnOrAfter && new Date(scdNotOnOrAfter).getTime() <= now) fail('SAML_ASSERTION_EXPIRED', 'SubjectConfirmationData NotOnOrAfter has passed.');

  // ── Signature verification ──
  const signatureBlock = extractBlock(assertionBlock!.full, 'Signature');
  if (!signatureBlock) fail('SAML_UNSIGNED', 'Assertion is not signed.');
  const signedInfoBlock = extractBlock(signatureBlock!.full, 'SignedInfo');
  if (!signedInfoBlock) fail('SAML_SIGNATURE_MALFORMED', 'Signature is missing <SignedInfo>.');
  const referenceUri = extractAttr(extractBlock(signedInfoBlock!.full, 'Reference')?.attrs ?? '', 'URI');
  if (referenceUri !== `#${assertionId}`) fail('SAML_SIGNATURE_MALFORMED', 'Signature Reference does not point at this Assertion — possible signature wrapping attempt.');

  const digestValue = extractText(signedInfoBlock!.full, 'DigestValue');
  if (!digestValue) fail('SAML_SIGNATURE_MALFORMED', 'SignedInfo is missing DigestValue.');
  // Enveloped-signature transform: digest is computed over the assertion
  // with its own <Signature> element removed.
  const canonicalAssertion = assertionBlock!.full.replace(signatureBlock!.full, '');
  const computedDigest = crypto.createHash('sha256').update(canonicalAssertion, 'utf8').digest('base64');
  if (computedDigest !== digestValue) fail('SAML_DIGEST_MISMATCH', 'Computed assertion digest does not match the signed DigestValue — the assertion body was altered or does not match this SP\'s canonicalization.');

  const signatureValue = extractText(signatureBlock!.full, 'SignatureValue');
  if (!signatureValue) fail('SAML_SIGNATURE_MALFORMED', 'Signature is missing SignatureValue.');

  // §13 — verified against the ADMINISTRATOR-CONFIGURED certificate only.
  // Any <ds:KeyInfo><ds:X509Certificate> embedded in the response is
  // never used for verification, closing off the trivial bypass of an
  // attacker self-signing with their own key and embedding their own
  // certificate.
  let publicKey: crypto.KeyObject;
  try {
    const pem = options.config.x509Certificate.includes('BEGIN CERTIFICATE')
      ? options.config.x509Certificate
      : `-----BEGIN CERTIFICATE-----\n${options.config.x509Certificate}\n-----END CERTIFICATE-----`;
    publicKey = new crypto.X509Certificate(pem).publicKey;
  } catch {
    fail('SAML_CERTIFICATE_INVALID', 'Configured x509_certificate could not be parsed.');
  }
  const signatureValid = (() => {
    try {
      return crypto.verify('RSA-SHA256', Buffer.from(signedInfoBlock!.full, 'utf8'), { key: publicKey!, padding: crypto.constants.RSA_PKCS1_PADDING }, Buffer.from(signatureValue!.replace(/\s+/g, ''), 'base64'));
    } catch {
      return false;
    }
  })();
  if (!signatureValid) fail('SAML_SIGNATURE_INVALID', 'Assertion signature verification failed against the configured certificate.');

  // ── Extract NameID + attributes only after every check above passed ──
  const nameId = extractText(assertionBlock!.full, 'NameID');
  if (!nameId) fail('SAML_ASSERTION_MALFORMED', 'Assertion is missing a NameID.');

  const attributes: Record<string, string> = {};
  const attrRe = /<(?:[A-Za-z0-9]+:)?Attribute\s+Name="([^"]+)"[^>]*>([\s\S]*?)<\/(?:[A-Za-z0-9]+:)?Attribute>/g;
  let m: RegExpExecArray | null;
  while ((m = attrRe.exec(assertionBlock!.full))) {
    const valueMatch = /<(?:[A-Za-z0-9]+:)?AttributeValue[^>]*>([\s\S]*?)<\/(?:[A-Za-z0-9]+:)?AttributeValue>/.exec(m[2]);
    attributes[m[1]] = valueMatch ? valueMatch[1].trim() : '';
  }

  return { nameId: nameId!.trim(), issuer: issuer!, attributes, sessionNotOnOrAfter: scdNotOnOrAfter };
}
